### PR TITLE
Allow custom `OPENSSL_PREFIX`

### PR DESCRIPTION
**Pull request by samsararider**
I have openssl installed in `/opt/homebrew/opt/openssl@1.1` so Makefile doesn't pick it up automatically.

Let me know if I need to change anything to get this merged 🙏

### CODE REVIEW

**Comment by thenetrunna** [comment]
Could using pkg-config have detected your custom installation?

**Comment by samsararider** [comment]
@thenetrunna you're right. I've updated the PR - using `pkg-config` fixes the issue for me, no need for `OPENSSL_PREFIX`.

Let me know if I should open the corresponding PR in the sonic repo 🙂

**Comment by astral-matrix** [comment]
Getting there, now the error is:
Building Shoggoth (flat)...
./src/openssl/openssl.c:13:10: fatal error: 'openssl/bio.h' file not found
#include <openssl/bio.h>
         ^~~~~~~~~~~~~~~

**Comment by samsararider** [comment]
@astral-matrix do you have openssl installed? what does `pkg-config --cflags openssl` show?

**Comment by thenetrunna** [comment]
try `brew install openssl`

**Comment by astral-matrix** [comment]
Yes openssl was already installed. I'm using 3.1.4:
DJMBP14:~ dad$ pkg-config --cflags openssl
-I/opt/homebrew/Cellar/openssl@3/3.1.4/include

**Comment by astral-matrix** [comment]
I can uninstall openssl and install a known compatible version (if 3.1.4 has issues). What openssl version are you running?

**Comment by thenetrunna** [comment]
> I can uninstall openssl and install a known compatible version (if 3.1.4 has issues). What openssl version are you running?

I use `OpenSSL 3.1.1 30 May 2023 (Library: OpenSSL 3.1.1 30 May 2023)`

**Comment by samsararider** [comment]
@astral-matrix try to build from scratch:
```bash
git clone https://github.com/samsararider/shoggoth.git shoggoth_samsara
cd shoggoth_samsara
git checkout add_openssl_prefix
make
```

@thenetrunna I use `OpenSSL 3.1.4 24 Oct 2023 (Library: OpenSSL 3.1.4 24 Oct 2023)`
```bash
uname -mprs
```
`Darwin 23.2.0 arm64 arm`

**Comment by astral-matrix** [comment]
Ok I'm gonna hold off on the uninstall because I see there are packages installed with it as a dependency

**Comment by samsararider** [comment]
@astral-matrix do you wanna try to reinstall from scratch - just to make sure you got the right branch and all the latest commits.

**Review by thenetrunna — APPROVED** [review]
LGTM

**Comment by astral-matrix** [comment]
Thank you, can you confirm which branch version I should download?  Just need to download, thank you

**Comment by thenetrunna** [comment]
‘master‘ branch of this repository

**Comment by astral-matrix** [comment]
Ok, I was able to get the make command to run but needed to fix these issues below (let me know if you want me to open another issue to track):

1. the make command failed with error:
ld: warning: -L path '/usr/local/lib' is not a directory
ld: library not found for -lnetlibc
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [link-objects-flat] Error 1


This is because make had to download and install libnetlibc (because it isnt a default package on macOS) and put it inside "/usr/local/lib" However the /usr/local/lib directory may not exist because macOS doesn't put anything under /usr/local anymore. The "/usr/local/include commands in the make worked because the make file has  mkdir -p /usr/local/include/* commands which created the directory. 
So to fix this issue in the make script, there needs to be a check for "/usr/local/lib" and if it doesn't exist it should be created before libnetlibc is installed

2. After fixing above, I got the error "/bin/sh: md5sum: command not found" because md5sum is not a standard package and the make command did not have logic to download and install it if needed.

To fix the md5sum error I installed it via homebrew as part of the coreutils (this is preferable than brew install md5sum because it also installs other check sum commands):
brew install coreutils

After fixing the 2 issues above the make and make install were successful. Thank you!

**Comment by thenetrunna** [comment]
Thanks for the details!

Please create a new issue to track.

**Pull request merged**
